development:
  adapter: mysql
  database: textbuster-dev
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  password: ruby

test:
  adapter: mysql
  database: textbuster-test
  pool: 5
  timeout: 5000
  host: 127.0.0.1

production:
  adapter: mysql
  database: textbuster
  username: textbuster
  password: asv1T8s8t
  pool: 5
  timeout: 5000
  host: 127.0.0.1

